// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzwqnrvtkjlcqboqlcdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6d3FucnZ0a2psY3Fib3FsY2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzEwNzgsImV4cCI6MjA2NTI0NzA3OH0.s02b1SXk7IJ3KHkr7khs_58ZGa60I1dj9s4sxOwgL8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);